### ISSUE TITLE
Strange lines in plot using ts_plot

### ISSUE THREAD

**Issue by rayms** [mkearney/rtweet#114]
I am generating plots using the code to plot multiple time series by filtering data with the "text" variable and in certain themes (e.g. minimal, spacegray, etc.) I am encountering weird artifacts/lines in the plot that have no relevance to the filtered data. I am attaching a file here as an example. Is this normal? How can I remove the unwanted white lines? 

![artifacts](https://user-images.githubusercontent.com/8173076/30864813-16c510d0-a2d5-11e7-9689-7e6af913953a.PNG)

**Comment by mkearney** [comment]
@rayms Couple of things:

## Update rtweet

Make sure you have an updated version of rtweet. I recommend the Github version.

``` r
## install devtools if it's not already installed
if (!requireNamespace("devtools", quietly = TRUE)) {
  install.packages("devtools")
}
## install dev version of rtweet from Github
devtools::install_github("mkearney/rtweet")
```

The most recent CRAN version would be the next best thing

``` r
install.packages("rtweet")
```

## ggplot2 is your friend

The themes were fun to make---and I learned a lot making them---but you're better off using [ggplot2](https://github.com/hadley/ggplot2) for generating plots. The `ts_plot()` function will still be useful, but you'll want to use the object returned by it rather than the default plot.

``` r
## load rtweet
library(rtweet)

## get the last 3200 tweets posted by Lebron James
lj <- get_timeline("KingJames", n = 3200)
sc <- get_timeline("StephenCurry30", n = 3200)

## merge into single data frame
rt <- rbind(lj, sc)

## ts_plot default
p <- ts_plot(rt)

## view default plot
p
```

![ts_plot_default](https://user-images.githubusercontent.com/13401460/30872135-b28da3dc-a2ae-11e7-9857-9d4ac238ed95.png)

By week

``` r
(p <- ts_plot(rt, "weeks"))
```

![ts_plot_weeks](https://user-images.githubusercontent.com/13401460/30872178-d28699a0-a2ae-11e7-894f-b6bee4ede43e.png)

By month

``` r
(p <- ts_plot(rt, "months"))
```

![ts_plot_months](https://user-images.githubusercontent.com/13401460/30872183-d894dd5c-a2ae-11e7-8818-7d3d076dbc39.png)

Since `p` is not a ggplot2 object, you can build on it. For example, add pretty labels:

``` r
## add labels
p <- p + ggplot2::labs(
  x = "Date",
  y = "Number of statuses",
  title = "How often do @KingJames and @StephenCurry30 tweet?",
  subtitle = "Monthly counts of tweets posted by Lebron James and Stephen Curry"
)
```

Add a ggplot2 theme

``` r
## add a ggplot2 theme
p + ggplot2::theme_dark()
```

![ts_plot_dark_theme](https://user-images.githubusercontent.com/13401460/30872072-8487b9aa-a2ae-11e7-9dd0-e9db522e9f72.png)

Or use the [ggthemes](https://github.com/jrnold/ggthemes) package.

``` r
p + ggthemes::theme_fivethirtyeight()
```

![ts_plot_fivethirtyeight](https://user-images.githubusercontent.com/13401460/30872076-8afc4b0c-a2ae-11e7-9a82-9f64ba2408ec.png)

Or create your own custom theme

``` r
## colors
dark <- "#333333"
light <- "#f0f0f0"

p +
  ggplot2::scale_color_manual(values = c(`KingJames` = "maroon", `StephenCurry30` = "cornflowerblue")) +
  ggplot2::theme_void(base_size = 12, base_family = "Roboto Condensed") + 
  ggplot2::theme(
    plot.margin = ggplot2::margin(.75, 2, 0, .75, "lines"),
    plot.title = ggplot2::element_text(face = "bold", size = ggplot2::rel(1.4)),
    plot.subtitle = ggplot2::element_text(size = ggplot2::rel(1.2)),
    legend.title = ggplot2::element_blank(),
    legend.position = "bottom",
    panel.background = ggplot2::element_rect(fill = light, colour = light),
    plot.background = ggplot2::element_rect(fill = light, colour = light),
    panel.grid.major = ggplot2::element_line(size = ggplot2::rel(.05), colour = dark),
    panel.grid.minor = ggplot2::element_line(size = ggplot2::rel(.025), colour = dark),
    axis.text = ggplot2::element_text(size = ggplot2::rel(.85), colour = dark),
    text = ggplot2::element_text(colour = dark),
    legend.text = ggplot2::element_text(size = ggplot2::rel(.95))
  )
```

![ts_plot_custom](https://user-images.githubusercontent.com/13401460/30872099-9ee96cd0-a2ae-11e7-8797-5ec38a5ea140.png)

Use dplyr's mutate functiont to create a grouping variable. Then use `ts_data()` to gather time series by group.

``` r
rt %>%
  dplyr::mutate(about_bball = grepl("nba|ball|game|play", text, ignore.case = TRUE)) %>%
  dplyr::group_by(about_bball) %>%
  ts_data("months", group = "about_bball")
```
