### ISSUE TITLE
Searching and saving tweets of an specific user between two given dates

### ISSUE THREAD

**Issue by matterlandsen** [mkearney/rtweet#129]
Hi,
I'm trying to search and save tweets of an specific user between two given dates, as follows:

`library(rtweet)
appname <- "CATpaperRtweet"
key <- "key_token"
secret <- "secret_token"
twitter_token <- create_token(app = appname, consumer_key = key, consumer_secret = secret)

account <- "A_RoyoMarine"
account

archivo <- get_timeline(account, n = 3200, parse = TRUE, since = 2016-08-16, until = 2016-09-11)

save_as_csv(archivo, file_name = "Marine06")`

I did try to change since and until for max_id, but it didn't work either. I'm only getting the last 3200 tweets of that user.

Any idea or help?

Thanks a lot!

**Comment by mkearney** [comment]
First, you'll want to make sure to pass the since and until dates as strings:

``` r
archivo <- get_timeline(
  account, n = 3200, parse = TRUE, since = "2016-08-16", until = "2016-09-11"
)
```

Second, I could be wrong, but I believe Twitter's publicly available timeline API only allows you to access to the most recent 3200 tweets. With those tweets, it is likely possible to narrow down queries using since and until parameters, but you can't use those to go beyond the 3200 tweet limit.
