### ISSUE TITLE
not getting full text from tweets

### ISSUE THREAD

**Issue by mtmcbride** [mkearney/rtweet#142]
I read that by default stream_tweets() should get the full text of each tweet, but this has not been the case for me. I tried installing from cran and from github, and for both versions, stream_tweets('Obama') returns many truncated tweets.

**Comment by mkearney** [comment]
@mtmcbride You should be getting the full text of all non-retweet and non-quote statuses.

I tested this by running streaming a random sample of tweets for 2 minutes.

``` r
> rt <- stream_tweets("", timeout = 120)
Streaming tweets for 120 seconds...
Downloading: 2.4 MB     Finished streaming tweets!
opening file input connection.
 Imported 1568 records. Simplifying...
closing file input connection.
```

Count the number of statuses that have truncation dots.

``` r
> sum(grepl("…\\s{0,}$", rt$text))
[1] 322
```

Count the number of statuses that have truncation dots but are **NOT** retweets or quotes.

``` r
> sum(grepl("…\\s{0,}$", rt$text) & !rt$is_quote & !rt$is_retweet)
[1] 2
```

View text of two potentially truncated statuses.

``` r
> rt$text[grepl("…\\s{0,}$", rt$text) & !rt$is_quote & !rt$is_retweet]
[1] "六佐くんに言われたね、「抱かれるしか脳がない癖に」って言葉で、内心大荒れしてたんですよ…\nそんなことない、そんなはずない、僕はお父様の役にたってる！！って………"
[2] "Que hubo!, me da mucho gusto que vengas a visitarme bueno hoy mismo vas a poder descargar peliculas quentin tarantino en hdrip ya sabes que…"                
```

Looking at the tweets in the web browser, it's clear those dots were actually entered by the users and not due to Twitter's stream API truncating them.

<img width="633" alt="screen shot 2017-11-27 at 1 05 21 pm" src="https://user-images.githubusercontent.com/13401460/33284220-ef2879a2-d373-11e7-945f-a97ae4a0c5b3.png">


<img width="635" alt="screen shot 2017-11-27 at 1 03 44 pm" src="https://user-images.githubusercontent.com/13401460/33284077-7382e364-d373-11e7-96ef-88f39ed4a8de.png">


 If you're using the REST API, you should be able to recover the full text using the `retweet_text` and `quoted_text` columns. Otherwise, you may have to run an additional `lookup_statuses()` using the `retweet_status_id` and `quoted_status_id` values.

**Comment by mtmcbride** [comment]
Thanks for the clarification.

**Comment by mtmcbride** [comment]
I'm sorry if I'm missing something, but I ran "test = stream_tweets("Obama")", printed all of the tweets that are not quotes and not retweets, and I still got a lot of truncated tweets.
![truncated_tweets](https://user-images.githubusercontent.com/25041439/33408977-1f51feee-d547-11e7-8104-837532b93fca.png)
