### ISSUE TITLE
lat_lng NAs

### ISSUE THREAD

**Issue by halgordon** [mkearney/rtweet#150]
I think the lat_lng function has a bug. I believe the the function is supposed to take the mean point form bbox_coords and then, if that is NA, replace it with a value from geo_coords or coords_coords. It does the first thing correctly, but not the second thing. I tired to follow along with your code, and I think that you may have confused yourself when you renamed coords. In the function update_if_na, I don't see how (!all(lengths(coords) == 2L)) will ever be FALSE (so you never actually run the rest of the code in that function). This results in observations without a bounding box not being replaced with their values from geo_coords and remaining NAs.

I also have a more philosophical question. It seems like the geodata in geo_coords is more precise than the data in bbox_coords. Shouldn't, when tweets report values for both variables, the geo_coords variable be the default instead of the bbox_coords?

**Comment by mkearney** [comment]
You're right. Thanks for pointing that out!

**Comment by mkearney** [comment]
@halgordon Thanks for this post. In addition to the confusing code error, I had also managed to read Twitter's API documentation correctly, but implemented the priority of the coordinates values backwards (I've explained it below for future reference or if anyone happens to search through issues looking for this sort of thing). It should be functioning properly now. I've also made sure the function will now preserve any users data attribute as well.

### Coordinates supplied by Twitter's API

Technically, Twitter's API returns up to three different geographical coordinate values.
- **place > bounding_box > coordinates**: c(lng_sw, lng_se, lng_ne, lng_nw, lat_sw, lat_se, lat_ne, lat_nw) longitude X 4, latitude X 4 points returned as the `bbox_coords` column.
- **[coordinates > coordinates]**: c(lng, lat), longitude, latitude points returned as the `coords_coords` column.
- **[geo > coordinates]**: c(lat, lng), latitude, longitude points returned as the `geo_coords` column (note: this has been deprecated by Twitter in favor of the consistent *lng, lat* format returned by `coords_coords` (from my understanding, these values are the same only flipped). 

According to Twitter's API documentation, `coords_coords` is more precise than `bbox_coords` because it's the result of geo-enabled location tracking coming from the actual intersection where the tweet was sent. The values supplied by `bbox_coords`, on the other hand, are associated with a `place`, which Twitter's API describes as 

> Place...When present, indicates that the tweet is associated (but not necessarily originating from) a Place.

Based on my reading of Twitter's [help documentation](https://help.twitter.com/en/using-twitter/tweet-location), it seems some places may only be available if a user is within a certain geographical proximity. However, other places selected by users–e.g., general locations–may not be restricted by the user's physical location.

<img width="540" alt="screen shot 2017-12-15 at 7 27 32 am" src="https://user-images.githubusercontent.com/13401460/34044613-47755f76-e16b-11e7-9327-9d000a77fb83.png">
