### ISSUE TITLE
I cannot create a token with rtweet package

### ISSUE THREAD

**Issue by skjainmiah** [mkearney/rtweet#157]
When i executed below code to create a token it showing me an error

```
create_token(app = "mytwitterapp", consumer_key, consumer_secret,
set_renv = TRUE)
```
Error in init_oauth1.0(self$endpoint, self$app, permission = self$params$permission, :
Unauthorized (HTTP 401).

can you please help me to get out it. plz

**Comment by mkearney** [comment]
@skjainmiah  99% of the time this is due to not setting `http://127.0.0.1:1410` as the callback URL. You can do edit that value in your app here: https://apps.twitter.com

**Comment by rmoor** [comment]
I have the callback setting right and still can load the token. When I run 
identical(token, get_token())
it returns "False".

Can you please help me out?

**Comment by mkearney** [comment]
Check to make sure you've installed most recent version of rtweet

``` r
install.packages("rtweet")

## it should be at least 0.6.8
packageVersion("rtweet")
```

Check your `.Renviron` file. I'd recommend just deleting any line starting with `TWITTER_PAT=`. The code below will open the file, which you can edit by deleting any line starting with `TWITTER_PAT=`.

``` r
file.edit("~/.Renviron")
```

Finally, restart R/Rstudio and create the token again.

If that still doesn't work, you can re-edit your `.Renviron` file and then instead of creating a new token, just run a simple search (like the code does below). A browser should pop open asking you to authorize rtweet's embedded client (rstats2twitter). Internally, a token is created and saved for you, though it will have `read-only` access (you can't post tweets, read DMs, etc.).

``` r
rt <- rtweet::search_tweets("lang:en")
```

**Comment by mkearney** [comment]
If the above suggestions don't work, please copy/paste as much code/error messages as possible (feel free to anonymize any token keys of course). These are the most common impediments to people using the package, so I want to make sure I'm aware of all possible hiccups!

**Comment by rmoor** [comment]
Thanks mkeareny. It seems to be working. Though it still returns from the "identical" command. But manually checking the info from get_token () and token shows the same key and project names.
Appreciate it!
