### ISSUE TITLE
Do you rturn likes

### ISSUE THREAD

**Issue by pssguy** [mkearney/rtweet#16]
"GET favorites/list
Returns the 20 most recent Tweets liked by the authenticating or specified user."

if not, that would be an enhancement I'd be interested in

**Comment by mkearney** [comment]
The function is written, just need to check some things, so I'm actually hoping to commit a `get_favorites()` function today!

**Comment by pssguy** [comment]
Excellent
Is that it for what is available from the APIs for tweet 'engagements'?
I mean things like link/profile clicks

**Comment by mkearney** [comment]
There's also an ads-API, but Twitter places a lot more restrictions on that data. Otherwise,  that's about it. Twitter's API can also return a list of muted accounts, but that's limited to the origin/user's account.

If you wanted to download your own analytics data, Twitter will generate a CSV for you. You'll need to setup your account at [analytics.twitter.com](https://analytics.twitter.com) (if you haven't already) and then click on the "tweets" tab , and that should get your there.

**Comment by pssguy** [comment]
Thanks. Let me know when the get_favorites() function is up, please

**Comment by pssguy** [comment]
Yes I had seen own analytics data which is helpful. However, it would be useful to see further engagement with other tweeters e.g hashtag clicks but certainly retweets/replies and likes gives a good indication of who to keep following

**Comment by mkearney** [comment]
get_favorites() has been added to rtweet!

**Comment by pssguy** [comment]
Cheers
having problems understanding this
get_favorites(user, n = 3000...
n	Specifies the number of records to retrieve. Must be less than or equal to 200; defaults to 3000,

I tried a couple of users and got 199 records for each

**Comment by mkearney** [comment]
Made a last second edit. And I was too confident and too impatient to wait until rate limit reset to run my tests. Should be fixed now. But, in honor of talk like a pirate day, I will to express my frustration with myself:

AAARRRRRRRRGH!
