### ISSUE TITLE
problem getting large amounts of followers

### ISSUE THREAD

**Issue by llsigerson** [mkearney/rtweet#168]
Hi,
I'm trying to get all the followers for someone who has more than 75000, using the retryonratelimit argument. It looks like the function gets the first batch of followers, waits for the reset, but then fails on the second batch. I've tried this with both the developmental and CRAN versions, and got the same results. It doesn't seem to depend on the user, or the n value either. Any help would be much appreciated!

Here's the code I used and output:
followers<- get_followers("ddale8", n= 1000000, retryonratelimit = T)
60000 followers!
Waiting about 13.7 minutes for rate limit reset...
Waiting about -0.1 minutes for rate limit reset...
Error in Sys.sleep(as.numeric(rl$reset, "secs") + 2) : 
  invalid 'time' value

**Comment by Isaacsh** [comment]
I've encountered the same problem today.

lamb_flw <- get_followers("Lamborghini", n = 1678182, retryonratelimit = T)
10000 followers!
Waiting about 14.7 minutes for rate limit reset...
85000 followers!

> length(lamb_flw$user_id)
[1] 10005

**Comment by rayms** [comment]
Just to say that I'm also receiving this error since last night. 

```
75000 followers!
Waiting about 14.8 minutes for rate limit reset...
Waiting about 0 minutes for rate limit reset...
Error in Sys.sleep(time) : invalid 'time' value
```

**Comment by mkearney** [comment]
I'm running code to try to replicate this now @Isaacsh, @llsigerson, and @rayms. Has this been a consistent error, or does this only happen sometimes?

My guess are:

1. Update to most recent version of rtweet. I know @llsigerson already did that and still got the error message, but I seem to remember making a fix on this one in the past.

2. You've reached the global rate limit or you're perhaps making competing `get_followers()` calls that are causing you to hit the rate limit. The problem is the internal `rate_limit()` call is not returning what it's supposed to. That's usually a sign that you've hit your global limit. I can probably remove the rate limit check inside the function, but might not get to it for a bit (if I took that out, I'd want to replace it with a stored value that I can update within the function; so it's not just a matter of deleting some code).

**Comment by Deuana** [comment]
I've encountered the same error. Even if the value of n for the current number of followers, the same error message is displayed.
pres <- get_followers("potus", n = "all",  retryonratelimit = TRUE)
75000 followers!
Waiting about 13.1 minutes for rate limit reset...
Waiting about -0.2 minutes for rate limit reset...
Error in Sys.sleep(as.numeric(rl$reset, "secs") + 2) : 
  invalid 'time' value

**Comment by NadarBharat** [comment]
Hello im still facing above error

Waiting about -0.2 minutes for rate limit reset...
Error in Sys.sleep(as.numeric(rl$reset, "secs") + 2) : 
  invalid 'time' value

**Comment by dasingh92** [comment]
@mkearney  this error still exists. I tried latest version from GitHub, but to no effect. I'm using rstudio on Manjaro Linux OS. All 3 (rtweet, rstudio and OS) are updated to latest versions.
