### ISSUE TITLE
How to grab tweet texts with more than 140 characters?

### ISSUE THREAD

**Issue by marvinmilatz** [mkearney/rtweet#183]
Hi all, 

first of all, thanks for the great package! 

I noticed that the standard API setting for Tweet texts is still limited to 140 characters. Apparently, you can grab extended Tweets via the command "tweet_mode=extended". However, this returns only NAs for the text variable. How can I fix this? Any help is much appreciated! Thanks! - Marvin

Here's a link to the text length part in Twitter's API Documentation: https://developer.twitter.com/en/docs/tweets/tweet-updates

Here's what I tried to achieve (just add a working hashtag):

`t <- search_tweets(q = "#XYZ", 
              n = 18000, 
              type = "recent",
              include_rts = TRUE,
              geocode = NULL, 
              max_id = NULL, 
              parse = TRUE, 
              usr = TRUE, 
              token = NULL,
              retryonratelimit = TRUE, 
              tweet_mode = "extended",
              lang = "de",
              verbose = TRUE)`

**Comment by JBGruber** [comment]
I noticed the same problem today. I think `tweet_mode = "extended"` is not passed on correctly or the json result is not converted right. In other words, this seems to be a bug.

# Test
```
Twitter <- get_timeline(user = "PeoplesMomentum",             
                        n = 320, 
                        max_id = NULL, 
                        home = FALSE, 
                        parse = FALSE,
                        check = TRUE,
                        #since_id = sinceID,
                        token = token)[["V1"]]

> Twitter[[1]]$display_text_range[[196]]
[1]   0 140
> Twitter[[1]]$truncated[[196]]
[1] FALSE
> Twitter[[1]]$text[[196]]
[1] "RT @jeremycorbyn: .@Theresa_May voted to triple tuition fees and saddle students with an average £40,000 in debt.\n\nThere's no need to \"revi…"
```
Here is the original Tweet which is longer than the 140 characters suggested by  display_text_range:
https://twitter.com/jeremycorbyn/status/965535594037350400

It is strange, since some Tweets seem to be retrieved in full length (One has 241 character for example) but this one is clearly truncated.

# tweet_mode
I looked into your code and found that `tweet_mode=extended` seem to be always set to extende in e.g., timeline.R:

```
params <- list(
    user_type = user,
    count = count,
    max_id = max_id,
    tweet_mode = "extended",
...)
```

So this should always be turned on---which I think makes sense because who would want truncated tweets. The code chunk from above also suggests that Tweets are not truncated by Twitter (Twitter[[1]]$truncated[[196]]). In fact `table(Twitter[[1]]$truncated)` returns that no tweets are truncated. But they are...


What is done to the tweets after rtweet gets them? Where could this go wrong? It would be great @mkearney if you could have a look at this. If you don't ave time, could you point us to where the conversion after the request from Twitter excatly happens? And how would you get the original return from Twitter? Maybe Twitter already delivers truncated tweets even when requested otherwise.

**Comment by mkearney** [comment]
Retweets and quotes will be truncated regardless of whether tweet_mode = "extended." That's why I added the `quoted_text` and `retweet_text` variables. Otherwise, I haven't observed any problems with returning the extended tweets.
