### ISSUE TITLE
lookup_users id/name ambiguity

### ISSUE THREAD

**Issue by geotheory** [mkearney/rtweet#225]
I've spotted a (very rare) error when performing a lookup_users call on a user who's screen name is the same as another user's id number: e.g. `lookup_users('12345678')` returns data for `@someone_else`.  Is this an inescapable behaviour of the API?  Might it be possible to tweak the function to accept an explicit `@`?  Happy to privately share an example account to test.

**Comment by mkearney** [comment]
@geotheory Ahh yes this is rare indeed. As of version `0.6.0` (I think) there has been an `as_screenname()` function that you can use to coerce it to screen name. Otherwise, for most functions that expect vector inputs of screen names or users IDs (major exceptions being `get_timeline()` and `get_friends()`), it'll determine whether you supplied screen names or user names (i.e., if one or more strings are not a valid user ID, it's assumed to be a vector of screen names) and sends them in batches with each request.

``` r

```

**Comment by geotheory** [comment]
OK thanks.  I guess a possible feature request (if you ever get this far down the list!) would be to add support for `get_timeline` and other `get_xxx` functions to accept the `as_screenname` object for single user queries.
