### ISSUE TITLE
How to process streaming data?

### ISSUE THREAD

**Issue by DataStrategist** [mkearney/rtweet#235]
So after messing around with these twitter streams for a while, it looks like if I wanted to for example do sentiment analysis on tweets on sharks in australia... I would have two options:

 1. Stream for 45 minutes, process the output file, and start streaming again. The problem with this method is that there's a 15 minute window where I'm not capturing tweets. I can't stream for 59 mins because there are actually quite some time-consuming operations even after capturing the tweets.*
 2. Stream consistently into a file, and then have another script every once in a while run some analyses on the json file. The problem with this method is that the log file can get HUGE really fast... so I would eventually need to delete the log file and start again? 

I guess what I would want (and i don't know if this is a reasonable feature request) is a kind of json file that keeps only I don't know... 100 tweets? constantly discarding old tweets and incorporating new ones... that way I could constantly analyze that file and perform some operations on it. That way I don't have either of the two problems outlined above.

Does my request make any sense?

* While I'm at it, I would also like to point out that it's very difficult to even predict how long these operations take... I only arrived at the 45/15 thorugh iteration... perhaps even this could be studied to better predict how long things will take? Although I guess it might be highly system dependent... and obviously on the number of tweets harvested.

**Comment by Arf9999** [comment]
Why not run two scripts in parallel on two sessions of R. While one streams, the other analyses. It should be fairly simple then to join the results and filter out any duplication.

**Comment by DataStrategist** [comment]
@Arf9999 Nice idea, but the API only allows for only one stream to be active at a time... I guess I could use two apps to harvest the same data but again that MUST be complicating things unnecessarily no? Is there no way to run a "tailing stream" or some such?

**Comment by Arf9999** [comment]
Alternatively, shorten the period of streaming (say 10 minutes), use 'parse = FALSE', and  use another R session to parse the JSON files saved. (The files are named fairly predictably e.g. 'stream-20180531125937.json' ) 

If the streaming script does't have to parse the file, the amount of time lost before it can start capturing a stream should be negligable.

By having your parsing script ignore the latest JSON file (which is still being written to), you should be able (theoretically) parse the others and then simply delete them.

I'm really not sure if this would work, but I can't see why not.

**Comment by DataStrategist** [comment]
hrm... indeed that does sound a bit better... I would still probably allow
some time for the unparsed file to save, but yeah, probably much less than
what I had before.

Still though... I mean, it sounds unwieldy, no? I'm curious as to how
people are using the streaming API that they don't have these problems!

**Comment by DataStrategist** [comment]
Yes! This is what I want! to save straight from the stream to a db... not sure it has to be Mongo... it could be a simple MySQL or even a SQLlite (oooo... I guess Mongo since the data comes in as a json... so that would be easiest it's true)... But I think that's the most elegant, no? So basically stream DIRECTLY into something?

@mkearney Is something like this possible?

**Comment by mkearney** [comment]
you can save the streaming output as json files (which can then be managed with mongo) and set `parse = FALSE`. There's also no limit on how long a stream can be open! But, otherwise, I haven't looked into a more hardwired way to integrate streaming with a specific database.

**Comment by mkearney** [comment]
I'm closing this now, btw, because the solution I think extends beyond rtweet's domain. You should  be able to manage the output json files by deleting/trimming a single file or by streaming in chunks into multiple files, saving the files, and then deleting those files once they've been analyzed.

**Comment by sefabey** [comment]
Seems like I like to revive closed rtweet issues. 

@mkearney, have you tried parsing large streams with your tweet parsing function? 

As you know, json files tend to expand when read into memory. This causes issues when json files are large (or RAM is low). I've been trying to stress test Twitter's API limits (to understand when are we getting rate limited). So, I thought running a sample with `lang="en"` would be good candidate for that. I run this for 48 hours and got a `json` file which takes 37.1gb space on disk. As I forgot to pass `parse=FALSE` to `stream_tweets` R automatically tried to parse the json file which crashed my Rocker instance on a machine with 64gb RAM.

I'm not sure if you'd be willing to add this to `rtweet` but my suggestion would be this: Can you write a function to write json files in hourly batches with date_time stamp attached to the file name? This would allow batch processing of hourly json files using `purrr:map` variants and prevent crashed caused by insufficient memory.

Alternatively, I assume one can split large json files into smaller chunks but not sure how that works.
