### ISSUE TITLE
search_tweets error

### ISSUE THREAD

**Issue by jerive31** [mkearney/rtweet#240]
Hi,

I've been trying to use the template to retrieve data and text from Twitter but continue to encounter an error when trying to run the search_tweets function.  I'm new to R and perhaps this has a simple solution, but I tried searching and haven't found anything particularly helpful and decided to pursue this option.  Hope someone out there can help and thanks in advance.  I'm running R 3.5 if that helps.

## search for 18000 tweets using the rstats hashtag
mytweets <- search_tweets("#rstats", n = 18000, include_rts = FALSE)

Error in `$<-.data.frame`(`*tmp*`, "reset", value = NA_character_) : replacement has 1 row, data has 0

**Comment by vhmedina** [comment]
Hello! I have the same issue. The traceback is the following

10: stop(sprintf(ngettext(N, "replacement has %d row, data has %d", 
        "replacement has %d rows, data has %d"), N, nrows), domain = NA)
9: `$<-.data.frame`(`*tmp*`, "reset", value = NA_character_)
8: `$<-`(`*tmp*`, "reset", value = NA_character_)
7: .rl_df(r)
6: rate_limit_(token, query, parse)
5: rate_limit.default(token, "search/tweets")
4: rate_limit(token, "search/tweets")
3: search_tweets_(q = "#rstats", 
       n = 2000, type = "recent", include_rts = TRUE, geocode = NULL, 
       max_id = NULL, parse = TRUE, token = <environment>, retryonratelimit = TRUE, 
       verbose = TRUE, since = 17680, until = 17681)
2: do.call("search_tweets_", args)
1: rtweet::search_tweets(query_aux, n = 2000, token = token, since = search_date - 
       1, until = search_date, retryonratelimit = T)

**Comment by Arf9999** [comment]
Something has definitely changed. Scripts that were working fine yesterday morning are now failing with this error. 

Has Twitter made a change to the API?

**Comment by maelle** [comment]
I re-created the app and token but it didn't help, I get the exact same error. cc @stephlocke

**Comment by hrbrmstr** [comment]
Twitter is having API issues right now
https://twittercommunity.com/t/application-rate-limit-status-broken/106429/3

**Comment by diplodata** [comment]
Twitter say "We’ve rolled back the change, and will monitor for further issues in this area". API is still down however.

**Comment by JBGruber** [comment]
My script ran normally this morning. It uses `get_timeline` and `search_tweets`. Both seem to work fine again.

**Comment by hrbrmstr** [comment]
timeline functions are still busted for me but the search works
