### ISSUE TITLE
Twitter login screen refuses to pop up, just provides error

### ISSUE THREAD

**Issue by Jennerz** [mkearney/rtweet#249]
I followed all the beginning stages of getting rtweet to work; however, when I put in a search option to have the log-in window pop up it refuses to.

It gives me the following error:

Error in init_oauth1.0(self$endpoint, self$app, permission = self$params$permission,  : 
  Unauthorized (HTTP 401).

**Comment by mkearney** [comment]
this is likely due to a change in defaults in your Twitter app found here: https://apps.twitter.com. Navigate to the `settings` tab and make sure the box next to `callback locking` is unchecked.


![screen shot 2018-06-12 at 3 50 41 pm](https://user-images.githubusercontent.com/13401460/41316637-7b379aa2-6e58-11e8-8ebb-731a79e977cf.png)

**Comment by Jennerz** [comment]
Hey Michael!

It still seems to not be working. I get the same error with the callback locking unchecked. I’m not sure what I’m doing wrong but I’ve been doing everything you say to do on the website. When I put in my API info, it gives me the error.

Jen
