### ISSUE TITLE
Feature Request: min_id argument in search_tweets()

### ISSUE THREAD

**Issue by Arf9999** [mkearney/rtweet#253]
I have a script that repeats a search for some specific terms a number of times over a period of time, 
`search_tweets() ` has an argument for `max_id` when iterating backwards for repeated searches in order to avoid getting duplicated results.

It would be great to have a similar argument for iterating forward with a new search, i.e. so as to only get new search results, not repetition. 

Any chance of a `min_id` argument in the future?

**Comment by JBGruber** [comment]
You can use `since_id`. It is not documented but passed to the API using the `...`.

**Comment by Arf9999** [comment]
Thanks, I've tried it but unsuccessfully, do I need to change the `status_id` type to an integer from a character?

I'll go read the API info...

**Comment by mkearney** [comment]
Since ID should work with a character. I'm traveling today but will test this tomorrow!

**Comment by JBGruber** [comment]
It works with a character indeed. I use it in a script which runs daily. I simply take the newest ID from the last search and use it as `since_id`. `since_id` needs to be a character for some reason. The query will then ignore the current `since_id` and all older tweets. Here is some code to reproduce/test it. First, make sure you have the newest rtweet and search for something:
```
> devtools::install_github("mkearney/rtweet")
Downloading GitHub repo mkearney/rtweet@master
from URL https://api.github.com/repos/mkearney/rtweet/zipball/master
Installing rtweet
'/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL '/tmp/RtmpNnGK3b/devtools10f57abe09fb/mkearney-rtweet-7b776d3'  \
  --library='/home/johannes/R/x86_64-pc-linux-gnu-library/3.5' --install-tests 

* installing *source* package ‘rtweet’ ...
** R
** data
*** moving datasets to lazyload DB
** inst
** tests
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (rtweet)
> library("rtweet")
> packageVersion("rtweet")
[1] ‘0.6.6’
> dir <- "/mnt/data/Dropbox/Twitter"
> tweets <- search_tweets(q = "#rstats",             
+                         n = 3200,
+                         token = readRDS(paste0(dir, "/Tokens/twitter_token.RDS")))
Searching for tweets...
Finished collecting tweets!
> nrow(tweets)
[1] 3123
> max(tweets$status_id)
[1] "1008451172951261186"
``` 
The resulting data.frame contains 3123 and the newest tweet has the id "1008451172951261186". I use this as the `since_id` and repeat the search:
```
> tweets <- search_tweets(q = "#rstats",             
+                         n = 3200,
+                         since_id = "1008451172951261186",
+                         token = readRDS(paste0(dir, "/Tokens/twitter_token.RDS")))
Searching for tweets...
Finished collecting tweets!
> nrow(tweets)
[1] 4
> min(tweets$status_id)
[1] "1008451172951261186"
```
The search resulted in just four new tweets and the smallest id is newer than newest from the last request (which means it worked). 

BTW, I'm not affiliated with this package but thought I'd share my knowledge since I profit from this package and really appreciate the hard work @mkearney  puts into this :)

**Comment by Arf9999** [comment]
Thanks for the feedback.  I have a search script looping and discarding duplicates and I don't want to interrupt it (it took a long time to get it not to cause memory problems on my freebie AWS instance). 

When it eventually crashes, I'll try again with` since_id`. 

Thanks for feedback, and I'm 100% with you on the fantastic resource that @mkearney has created. I really appreciate it as well.

I'm going to close this issue.
