### ISSUE TITLE
Timelines Between Dates: Previous Examples Not Working

### ISSUE THREAD

**Issue by kurtawirth** [mkearney/rtweet#312]
### Problem

When passing "since" and "until" to Twitter through get_timelines(), the results do not match the specified dates.

### Reproduce the problem

Example code: 

```r
result <- get_timeline("screenname", n = 100, parse = TRUE, since = "2019-02-01", until = "2019-02-04", type = "recent")
```

Which returns a dataframe with the user's most recent 100 tweets and disregards the "since" and "until":

```r
range(result$created_at)
[1] "2019-01-30 16:36:44 UTC" "2019-02-08 15:59:23 UTC"
```

### rtweet version

```r 
‘0.6.20’
```

### Session info

``` r
R version 3.4.3 (2017-11-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)
```

**Comment by Arf9999** [comment]
The Twitter standard API doesn't allow for "since" or "until" parameter (unlike the web interface) in `GET statuses/user_timeline `

In order to set a "since" date it is necessary to use a status_id from that date and use the "since_id = " parameter. The search will then deliver results from all tweets with a higher status_id. For "until", you'll similarly need to set a "max_id ="

https://developer.twitter.com/en/docs/tweets/timelines/api-reference/get-statuses-user_timeline.html

**Comment by kurtawirth** [comment]
I see, so limiting to a timeframe for a vector of users is impossible, then?

**Comment by Arf9999** [comment]
No. Just slightly more complex,  The status_ids that you use for the since_id and max_id are arbitrary (they don't need to come from that specific user_id/screen_name), as long as they correspond to the start and end points of your required search. 

So to set a "since" date of 2019-02-01, simply select a tweet from 31 Jan 2019 e.g. "1090887065456148481"
To set an "until dateof 2019-02-04, similarly choose a tweet from 5 Feb 2019 e.g. "1092889267674599424"

You can then get the timeline, and simply clean it up to remove any out of bounds dates.
'result <- get_timeline("screenname", n = 100,  parse = TRUE, since_id = ""1090887065456148481"", max_id = "1092889267674599424", type = "recent") %>%
dplyr::filter(created_at > "2019-01-31" & created_at <="2019-02-04")'

**Comment by kurtawirth** [comment]
Perfect. You're a godsend! To confirm: I had just come up with the same
idea and can confirm this method works.

**Comment by Arf9999** [comment]
If it is sorted, please close the issue.

**Comment by larissabr** [comment]
Hi, sorry to re-open this, but I'm trying the same code and the result is empty. I get a dataframe with 35 variables and 0 results. 
Any reason why it should be happening?

result <- get_timeline("governomg", n = 3200,  parse = TRUE, since_id = "1065345858152075265", 
                       max_id = "1480340719034372098", type = "recent") %>%
  dplyr::filter(created_at > "2018-11-21" & created_at <="2022-01-10")

**Comment by llrs** [comment]
Hi @larissabr, 
could you provide the version number you are using of rtweet? I assume you are using the version 0.7.0 just to confirm with which version should I check.
Could it be that the user governomg hasn't tweeted or received any tweet in the last 7 days?
It might be a problem with the API or rtweet, I would recommend to test the devel version of rtweet if you feel comfortable with the breaking changes (but I expect to release the new version in a month, so be prepared for them if you keep using rtweet).

**Comment by larissabr** [comment]
Hi! Thanks for replying ! This is the version: rtweet_0.7.0.9000, I updated from Github. 

My problem is that I need a specific timeframe and governomg has actually tweeted more than 3200 times in the past two years (my range is 2019 and 2022). I've been trying using search_fullarchive with the date parameters and that comes up with 

Error in `find_id()`:
! `max_id` must be a character vector or data frame

rlang::abort(paste0("`", arg_name, "` must be a character vector or data frame"))

**Comment by llrs** [comment]
@larissabr The current version of this repository is 0.7.0.9030, did you install it from a different repository?
However, the issue you mention about `search_fullarchive` is one present still on this version  that couldn't get around and fix it yet. 

Now that I look more closely to the code, I think the argument  `type = "recent"` does nothing. It might be the reason why you get an empty response or it might not be the case. But check without it.

**Comment by larissabr** [comment]
@llrs thanks, I've updated through the correct repository and other minor errors I was getting have stopped which is a relief. I removed the type = "recent" argument and it made no difference, still an empty response. Thanks for replying.

**Comment by llrs** [comment]
Ok, I hope that in a couple of weeks I can fix the bugs reported in #713 and #578, I'll ping you to test the fix too

Note: just adding this to link the issues to have a reminder

**Comment by larissabr** [comment]
Just to let you know, the below to get the first 3120 tweets. When I adjust the max_id to the oldest tweet it fetches so I can get whatever remains, it comes up empty. 

Thanks for your time!

mg <- get_timeline("governomg", n = 3200,  parse = TRUE, since_id = "1065345858152075265", 
                    max_id = "1480340719034372098", env_name = 'environmentname') %>%
  dplyr::filter(created_at > "2018-11-21" & created_at <="2022-01-10")

**Comment by larissabr** [comment]
> Sorry to come back to this too, but @larissabr have you or anyone found a solution? having the exact same issue, the results come back empty even though that user was posting in the time frame specified. thanks in advance!
@anjalabartolina I ended up asking for academic access and used academictwitteR
