### ISSUE TITLE
Geo-located tweets does not work.

### ISSUE THREAD

**Issue by jldelda** [mkearney/rtweet#33]
When I try to retrieve geo-located tweets it does not work. Would you know why it does not work?

This is exactly what I am using:
Zika_tw <- search_tweets("#Zika", n=100, type= "mixed", max_id = NULL, parse = TRUE, lang="pt", geocode="-22.9729560,-43.1954997")

When I remove the geocode, it works. But I definitely need tweets from one place. What do you recommend me to do?

**Comment by mkearney** [comment]
This should be as simple as adding a radius to your coordinates, e.g., "37.781157,-122.398720,10mi". You must specify "mi" or "km".

Side note: Assuming that fix works, you might consider dropping the hashtag sign from your search. Twitter recommends it, and in my experience the returned object includes all the same tweets plus some others. Not sure if it actually increases the number of hashtagged tweets, but something to consider.

Let me know how geocode goes. It's an area which I haven't been able to spend a lot of time checking yet.

Thanks for using rtweet and reporting the issue! It is much appreciated!

**Comment by jldelda** [comment]
Thank you very much Mkearney. But it still does not work correctly. 
I search for at least 10000 tweets and it only brings 45.

The last thing I tried was...

`Zika_tw <- search_tweets("Zika", n=10000, type= "mixed", max_id = NULL,parse = TRUE, lang="pt", geocode="-22.980542,-43.202548,20mi")`

**Comment by mkearney** [comment]
Well, I got the same result as you, so that's a good sign.

```{r}
> Zika_tw <- search_tweets(
+   "Zika", n = 1000, type = "mixed", verbose = FALSE,
+   max_id = NULL, parse = TRUE, lang = "pt",
+   geocode = "-22.980542,-43.202548,20mi")
> NROW(Zika_tw)
[1] 45
```

I was able to retrieve 423 tweets when I changed `type` to "recent".

```{r}
> Zika_tw <- search_tweets(
+   "Zika", n = 1000, type = "recent", verbose = FALSE,
+   max_id = NULL, parse = TRUE, lang = "pt",
+   geocode = "-22.980542,-43.202548,20mi")
> NROW(Zika_tw)
[1] 423
```

Up to 473 tweets by increasing the radius to `50mi`.

```{r}
> Zika_tw <- search_tweets(
+   "zika", n = 1000, type = "recent", verbose = FALSE,
+   max_id = NULL, parse = TRUE, lang = "pt",
+   geocode = "-22.980542,-43.202548,50mi")
> NROW(Zika_tw)
[1] 473
```

Up to 578 after dropping `lang` argument.

```{r}
> Zika_tw <- search_tweets(
+   "zika", n = 1000, type = "recent",
+   max_id = NULL, parse = TRUE, verbose = FALSE,
+   geocode = "-22.980542,-43.202548,50mi")
> NROW(Zika_tw)
[1] 578
```

This is about what I would expect. The problem could be that you're hoping to get tweets from closer to the Olympics? Unfortunately, Twitter's API only extends back 7-10 days. As of today, the oldest tweets you can get appear to be from late on Oct. 16th.

```{r}
> Zika_tw <- search_tweets(
+   "zika", n = 10000, type = "recent",
+   geocode = "-22.912214,-43.230182,500km")
> NROW(Zika_tw)
[1] 4829
> ts_plot(Zika_tw)
```
![zika](https://cloud.githubusercontent.com/assets/13401460/19732650/025a70d4-9b67-11e6-8c1c-14d439eeb1be.png)

**Comment by jldelda** [comment]
Thank you very much... but it is still strange to me. Why the "Since =" operator exists?

**Comment by mkearney** [comment]
It didn't make sense to me until I started collecting tweets of trends that had very high activity rates. I've returned several million tweets from a single day, so the ability to narrow your search from one day vs another provides at least some ability to focus on a specific date range.

**Comment by mkearney** [comment]
I used the `since` argument above because sometimes I think you get an extra day or two by specifying it. I think I debunked my theory though. So if you're easily recovering all of the tweets in one or two passes, then it doesn't really make a difference. When you get over a million tweets though, it can take a long time, and the since and until args come in handy.
