### ISSUE TITLE
Posting plots generated in R via post_tweet

### ISSUE THREAD

**Issue by jblumenau** [mkearney/rtweet#34]
Hi there, the title basically says it. I'd like to be able to generate a plot in R:

```
my_plot <- plot(rnorm(100), rnorm(100))
```

And then embed it as media in a tweet from `post_tweet`:

```
post_tweet(my_plot)
```

Is this possible?

Many thanks, and great package!

**Comment by mkearney** [comment]
Ahh, not yet! I started to look into attaching media to tweets, but stopped myself before I spent too much time spinning my wheels.

**Comment by jblumenau** [comment]
Ah, no worries, thanks anyway!

**Comment by jblumenau** [comment]
FWIW, I've just found that this is possible in the `twitteR` package:

```
library(twitteR)

jpeg("tmp.jpeg")
plot(rnorm(1000), rnorm(1000))
dev.off()
tweet("hi", mediaPath = "tmp.jpeg")
```
In case you would like to explore further!

**Comment by mkearney** [comment]
I played around with this a bit, but couldn't figure it out. Admittedly, I didn't have a lot of patience with reading through Twitter's (uploading media documentation)[https://dev.twitter.com/rest/media/uploading-media].

If anyone has any ideas, feel free to let me know. Otherwise, this is probably low on my priority list for a while.
