### ISSUE TITLE
some more result columns that shouldn't be doubles

### ISSUE THREAD

**Issue by ssyvert** [mkearney/rtweet#36]
I wasn't sure if I could reopen an issue, but this is a follow-up on #11 basically. I noticed that the output of search_tweets() returns a couple of columns as double that should really be characters:

status_id
user_id
mentions_user_id
retweet_status_id

No biggie as you can easily as.character() them, but I thought you might want to change the default.

**Comment by mkearney** [comment]
This was actually intentional for performance reasons. I'd happily convert them back to character if there's a reason to. They seem to behave well with R's double class. And considering how large data sets can get with this package, the performance boost has been worth it, at least in my experience.

What do you think? Do you think I should create an "as.double" arg and set character as default?

I'm working on leveraging c++ for added performance, so that may eventually force my hand one way or another but it'll probably be another month or two until that happens.

**Comment by ssyvert** [comment]
That seems like a fair way to approach it, and having it as.character by default would be less confusing for novices who are arguably more likely to just want to write.csv() and continue elsewhere with their results (write.csv writes the values as scientific notation that can't be changed back with precision in something like excel).

**Comment by mkearney** [comment]
Good call. I was worried about that happening when writing CSVs. I so rarely use them anymore, I should probably make it more of a habit given how widespread they are.

**Comment by mkearney** [comment]
Okay, `as_double` should now be integrated and available for all relevant functions. One days I'll remember to include language in my commit message to close the issue. But not today.
