### ISSUE TITLE
Error for filtered stream

### ISSUE THREAD

**Issue by methodds** [mkearney/rtweet#39]
Hi, 
first of all thank you for creating this awesome package! I just used ```stream_twitter``` to download filtered data and while it was working flawlessly on the first attempt, all other attempts failed with errors:

````
stream <- stream_tweets('trump, clinton', 30, token=token)
Streaming tweets for 30 seconds...
Downloading: 2.2 MB       kB     
Finished streaming tweets!
opening file input connection.
 Found 1000 records...
incomplete final line found on 'C:\Users\kasus\AppData\Local\Temp\RtmpiUQL6r\file1dec6db41121.json'closing file input connection.
incomplete final line found on 'C:\Users\kasus\AppData\Local\Temp\RtmpiUQL6r\file1dec6db41121.json'Error in rl[[seq_len(length(rl) - 1)]] : 
  attempt to select more than one element in vectorIndex
````
Do you have any idea whats the problem here? I first thought that my syntax is incorrect and you expect a vector for multiple keyterms, like ```c('trump', 'clinton')```, but this resulted in another error before even starting the stream.

**Comment by mkearney** [comment]
I'm glad you enjoy the package so far!

So I believe I've actually already discovered this problem and fixed what's happening here. The problem is I'm in the middle of a number of improvements to time series/plot functions, and I'm also in the middle of a conference, so I'm hesitant to push an update until I know everything's working.

In the short term, though, you should be able to set `parse = FALSE`, specify a `file_name`, and then manually fix the problem.

```{r}
stream <- stream_tweets("trump,clinton", timeout = 30, token = token, 
    parse = FALSE, file_name = "trumpclinton.json")
```

Then either open the file and add a blank line to the end of it, or you can do that through R:

```{r}
tc <- readLines("trumpclinton.json")
cat(paste0(tc, "\n"), file = "trumpclinton2.json")
```

Once that's done you should be able to parse the json file into a nice data frame:

```{r}
rt <- parse_stream("trumpclinton2.json")
head(rt)
```

**Comment by mkearney** [comment]
This issue should now be fixed. I'll also note that I've added parse_stream_xl(), which is handy for parsing especially large streaming json files.

**Comment by methodds** [comment]
Thank you! Just a small suggestion in this context: You could implement the parameter ``timeout`` such that a value like ``FALSE`` will let the stream run until interrupting the program manually. This would be very handy for long-term projects.

**Comment by mkearney** [comment]
I like it. In theory you should be able to set timeout to "Inf" and as long as you've provided a file_name, you should retain all data collected up until an interruption point. I suppose I could allow users to set timeout to false and implement those things internally (you'd also want to set parse to FALSE for example to avoid the inevitable error). Is this kinda what you mean?

**Comment by methodds** [comment]
Exactly, it would basically be a smooth quit without any errors :)
