### ISSUE TITLE
date-specific queries

### ISSUE THREAD

**Issue by lescai** [mkearney/rtweet#43]
Hi there,
I see in the to-do-list you mention documentation for date-specific queries.
are they possible already in the current version?
I've been searching a bit on the code but I must have missed this feature.

**Comment by mkearney** [comment]
The good news is that you already can (example code below). The bad news is Twitter's API limits searches to the past 10 days or so.

```{r}
q <- "data science"
n <- 1000
since <- "2016-12-01"
until <- "2016-12-05"
rt <- search_tweets(
    q = q, n = n, type = "recent", 
    since = since, until = until)
```

And you don't have to use both `since` and `until` (you could use one or the other), but I would recommend keeping `type = "recent"`.

**Comment by lescai** [comment]
thank you ;)

**Comment by NataliaUC** [comment]
Hi! 
I have tried using the lubridate package together with the rtweet one, to define `since=today()-ddays(6)` and `until=today()-ddays(1)`. I also set the type to recent. When I run my code no error comes up, however when I check the tweets that I get, they do not respond to the dates that I have set. Do you have any suggestions? 
Thank you!

**Comment by Ljupch0** [comment]
@NataliaUC possibly you have to call `as.character()` on the date object returned by lubridate before passing to rtweet
