### ISSUE TITLE
Improve documentation about n argument of search_tweets()

### ISSUE THREAD

**Issue by yutannihilation** [mkearney/rtweet#60]
The document of `n` says:

> Integer, specifying the total number of desired tweets to return.

But actually, more tweets than `n` are returned.

```r
l <- purrr::map(99:101, ~ search_tweets(q = "#rstats", n = ., token = twitter_token))
#> Searching for tweets...
#> Finished collecting tweets!
#> Searching for tweets...
#> Finished collecting tweets!
#> Searching for tweets...
#> Finished collecting tweets!

purrr::map(l, nrow)
#> [[1]]
#> [1] 100
#> 
#> [[2]]
#> [1] 100
#> 
#> [[3]]
#> [1] 200
```

I guess this is done by design, right? I really appreciate if this behavior is clearly documented :)

**Comment by mkearney** [comment]
Because Twitter's API rate limits apply to requests and not observations (e.g., tweets), the current the default is to return the max number of hits for the minimum number of required requests. So, since `search_tweets()` pulls 100 tweets [max] at a time, `n = 50` will return 100 tweets from 1 request, and `n = 250` will return 300 tweets from 3 requests. 

Of course, I could alter the nth request to be the exact remainder calculated using the `n` parameter, but that runs into another problem. Twitter's API will occassionally short the return (b/c of deleted tweets or other mysterious reasons), so in those cases `n` still won't be reliable unless the function sends an additional request to return only 1 or 2 observations. If API rate limits are the currency, then this practice would the equivalent of throwing money away.

You bring up a great point about documentation. Perhaps I will take what I've written for the two paragraphs above and move them to the documentation so this makes more sense.

I'm open to other ideas as well. So if you think of a better approach, I'd love your thoughts on it!

**Comment by yutannihilation** [comment]
Wow, thanks for the detailed explanation! 👍 

Sorry, I forgot this counterintuitive nature of Twitter API and I was too lazy to read the "Details" section, which describes it clearly...:

> Number of tweets returned will often be less than what was specified by the user.

I'm satisfied with your strategy and implementation :) I don't come up with any better idea.
But, just to clarify, my subtle surprise was that I got 100 tweets when I needed only 5, where number of tweets returned was *MORE* than what was specified by the user. I don't think this is a very common or important issue, but could you consider describing a bit that the results may be more than `n` in some cases?

**Comment by mkearney** [comment]
To give you an idea of my thought process, imagine a user wants a search about icecream to return 60 tweets.

```{r}
icecream <- search_tweets(""\ice cream\"", n = 60)
```

The outcome of making a API request for exactly 60 tweets is either (a) we get exactly 60 tweets or (b) we get fewer than 60 tweets. If we got 60 every time, there'd obviously be no problem. But let's say we only get 58 tweets. This is the dilemma. Either we just say, "sometimes you are going to get shorted even though there are in fact more tweets about ice cream there," or we send another request to Twitter for 2 tweets. This not only kills me inside (I'm frequently monitoring my API rate limits to maximize data calls, etc.), but it may often reproduce the original problem due to deleted tweets or whatever---that is, making an additional request for 2 tweets after the first request was shorted is likely to come up short again---which means we could be making 3 calls to get the same data (60 tweets) that we could get with a single call (i.e., `n = 100`).

So, if we toss that approach aside, here are what I think the remaining options are:

1. We make exact `n` requests to Twitter and let the results occasionally run short. This isn't that big of a deal, but, to me, it means that we have to accept that `n` won't always be equal to number of returned observations even in cases when the REST API actuallly has `n` observations to return.

2. We keep the current approach, but just before outputing the data frame we subset the data with `seq_len(n)` to return only the number of observations requested. This would create the most reliable* return object but it means we are throwing away observations simply to avoid explaining the internal mechanics of API requests (this is why I think your comment makes such a good point; I made a decision to benefit the user even though it may seem counter-intuitive...I probably shouldn't run away from explaining it).

3. (***the current implementation***) We make sure all requests are set to maximize returns by *only* requesting with intervals determined by single-call maximums. If we decide to accept that not all results will be reliable (like the first option), then why not maximize efficiency while we're at it? If a script requires a specific n, then users can always create wrapper functions or subset the returned data on their own.

```{r} 
search_n_tweets <- function(q, n, ...) search_tweets(q, n, ...) %>% .[1:60, ]
```

**Comment by philstraforelli** [comment]
Hi Mike,

I just wanted to chime in and say that improving the documentation regarding the `n` argument would be very helpful. I've been experimenting with your package and I was very confused as to the amount of tweets not matching the amount I specified. Just a note though (not something I particularly care about either way), but for some reason on my version (CRAN v0.4.0) the increase is 200 tweets at a time, instead of 100. So if I do `tweets <- search_tweets("@realDonaldTrump", n = 201, include_rts = FALSE, token = twitter_token)` I'm getting 400 tweets instead of 300. Again, this is more of an observation than an issue.
