### ISSUE TITLE
get_timeline() -  Complete confusion

### ISSUE THREAD

**Issue by pssguy** [mkearney/rtweet#66]
```
djt_sent <- get_timeline("realDonaldTrump", n = 2000)
```
Returns 2000 tweets that realDonaldTrump has sent

```
djt_received <- get_timeline("realDonaldTrump", n = 2000,home=TRUE)
````
Returns most recent 765 tweets that are on my timeline - nothing to do with realDonaldTrump

From API docs I see
"User timelines belonging to protected users may only be requested when the authenticated user either “owns” the timeline or is an approved follower of the owner."

Does that mean that it defaults to own in latter situation rather than throwing an error?
Also,   'approved follower'  does not seem to be the same as someone who follows me. I have tried entering such a screen_name and still get my timeline

**Comment by mkearney** [comment]
Setting `home = TRUEE` results in an GET statuses/home_timeline request, which, according to the [documentation](https://dev.twitter.com/rest/reference/get/statuses/home_timeline)....

*Returns a collection of the most recent Tweets and retweets posted by the authenticating user and the users they follow. The home timeline is central to how most users interact with the Twitter service.*

*Up to 800 Tweets are obtainable on the home timeline. It is more volatile for users that follow many users or follow users who Tweet frequently.*

What you have quoted is about the default (if `home = FALSE`) user timeline request. Although, I wonder if the clarification of being an approved follower is new? It almost sounds like you can only get Trump's tweets, for example, if you follow him. 

It could also be that for public accounts, everyone who isn't blocked is considered an "approved follower." This makes sense to me, kinda, because using the same API, you should be able to get timelines from private accounts that you do follow---so the language they have there is trying to emphasize that distinction....maybe?

**Comment by pssguy** [comment]
Just restarted R session and loaded token. Tried 4 different categories of user

```
#Follow and friend
a <- get_timeline("jalapic", home=TRUE) #195 mine
#neitheer follow nor friend
b <- get_timeline("vuorre",n=800,home=TRUE) #770 mine
#follow not a friend
c <- get_timeline("cpsievert",n=800,home=TRUE) #195 mine
#do not follow but a friend
d <- get_timeline("KseniyaMerych",n=800,home=TRUE) #775

```

in every instance I get MY home timeline back rather than that of the screenname. The 770 fits in better with  maximum  but then why 195 ?

```
sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_Canada.1252  LC_CTYPE=English_Canada.1252    LC_MONETARY=English_Canada.1252
[4] LC_NUMERIC=C                    LC_TIME=English_Canada.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rtweet_0.4.1

loaded via a namespace (and not attached):
[1] httr_1.2.1    magrittr_1.5  R6_2.2.0      tools_3.3.2   curl_2.3      jsonlite_1.2  openssl_0.9.6
```

Any chance you could try and replicate this

**Comment by mkearney** [comment]
So the problem is that when you specify `home = TRUE` you're asking to receive the timeline of the account associated with the token. By default, `home = FALSE` will return the timeline of whichever user you've specified with the user parameter. This works for me on 3 machines, and it works on the tests I've set up for it.

In theory, if you set home to TRUE, you should be getting *your* timeline. However, rtweet has a built-in token (with no write abilities), so you're getting the timeline associated with that (which follows a handful of #rsats accounts).

**Comment by mkearney** [comment]
I probably need to clarify these things in the documentation. You have made it clear that the documentation should emphasize that home timeline doesn't allow you to specify the user. It's automatically limited to the associated account.
