### ISSUE TITLE
Error when searching tweets with UTF-8 characters (search_tweets)

### ISSUE THREAD

**Issue by geri43** [mkearney/rtweet#72]
When I try to search tweets with utf-8 characters in them I get this error:
![image](https://cloud.githubusercontent.com/assets/11545220/24071804/3258dae8-0bdb-11e7-877e-d4b4c1224687.png)

**Comment by Crackz** [comment]
I have the same issue !! 
Is there any way to MAKE IT WORK

![untitled](https://cloud.githubusercontent.com/assets/12835589/24842075/3a29d592-1d92-11e7-93de-89518756ff7c.png)

**Comment by Crackz** [comment]
@geri43 
this bug is related to package httr as mentioned [ here](https://github.com/hadley/httr/pull/424) 

Quick Solution : i have distributed then applied fixes to httr package

just install it `devtools::install_github("Crackz/httr")`

**Comment by mkearney** [comment]
@Crackz any update on this? Has bug been fixed in httr?

**Comment by Crackz** [comment]
@mkearney Nope .. 
pull request of @yutannihilation is still open  
so i tested cran , github versions and the bug is still there

**Comment by yutannihilation** [comment]
Oh, I didn't notice `curl::curl_escape()` works here. This may be a good news...

**Comment by yutannihilation** [comment]
Umm, I couldn't understand why this kind of tweaks can be ok, which is suggested in #78:

```r
hashtag1 <- '忍殺'
all_tweets <- search_tweets(q=curl::curl_escape(hashtag1),
                            token=token,
                            n=180)
```

`curl_escape()` will escape this usual percent encoding.

``` r
curl::curl_escape(hashtag1)
#> [1] "%E5%BF%8D%E6%AE%BA"
```

And, if my understanding is correct, this string will be escaped once more by `oauth_encode1()` in httr. (This percent-encoding is described in [RFC 5849](https://tools.ietf.org/html/rfc5849#page-29), which is a bit different from the former one.)

```r
httr:::oauth_encode1(curl::curl_escape(hashtag1))
#> [1] "%25E5%25BF%258D%25E6%25AE%25BA"
```

I thought this string cannot be restored as it is escaped too much. But this definitely works. If this is OK, at least for Twitter, it may be better to adopt this as a quick workaround, since httr is no more maintained actively.

**Comment by yutannihilation** [comment]
Hi, my PR(https://github.com/r-lib/httr/pull/424) was merged at last, so soon we will be free from this error after the next release of httr :)
