### ISSUE TITLE
get_token seems to return non-twitter tokens

### ISSUE THREAD

**Issue by LucyMcGowan** [mkearney/rtweet#83]
I noticed if I'm working in another package that has a token, and I run your `get_tokens()` function, I get my previous tokens rather than my twitter tokens. It seems a bit strange - is this intentional?  Here is a quick example where I have a googlesheets token and then run `get_tokens()` and the output is my google token:
```
googlesheets::gs_auth(new_user = TRUE)
rtweet::get_tokens()
## <Token>
## <oauth_endpoint>
## authorize: https://accounts.google.com/o/oauth2/auth
## access:    https://accounts.google.com/o/oauth2/token
## validate:  https://www.googleapis.com/oauth2/v1/tokeninfo
## revoke:    https://accounts.google.com/o/oauth2/revoke
## <oauth_app> google
##  key:    
##  secret: <hidden>
## <credentials> access_token, expires_in, refresh_token, token_type
```

I was poking around a bit in the code & I don't fully understand it, but it may be from [this logic](https://github.com/mkearney/rtweet/blob/master/R/tokens.R#L223-L229).

**Comment by mkearney** [comment]
Yeah, it has to do with the sequence of calls made when looking for your Twitter token. If you've setup your environment variable correctly ([updated instructions here](https://mkearney.github.io/rtweet/articles/auth.html)), then it *should* find the Twitter token first, which would prevent the GS token mixup. (Thanks for the post, btw. This makes it clear I should add an endpoint validation check to prevent this from happening in the future). 

If sorting out your Twitter token environment variable doesn't do the trick, let me know, and I'll try to clean up this token fetching business sooner. Or, if you're still having issues with finding the correct environment variable, you may also want to checkout the current state of your .Renviron file to see if something has gone haywire. The code below will print out the file in your R console. Alternatively, you can enter `cat ~/.Renviron` in terminal/bash.

```{r}
con <- file.path("~", ".Renviron")
renv <- readLines(con)
close(con)
cat(paste(renv, collapse = "\n"), fill = TRUE)
```

I know I've managed to append directly onto an already filled line in my .Renviron file [at least] a couple of times. When that's happened to me, it looks something like this:

```
> TWITTER_PAT=/Users/mwk/twitter_token.rdsNYTIMES_KEY=asfd0987asfd0987a90sfda0789asfda0987afd
```

To fix this you could open the file in any text editor and insert the appropriate line break. What I'm getting at, in other words, is that if you've saved your environment variable, but `get_tokens` is *still* returning the GS token, then it could be that the .Renviron file (which contains the environment variables that are read into R on startup) isn't being parsed correctly. In my experience, this happens because something was added to a non-empty line.

Of course, this may not be the solution to your problem at all. If that's the case, I'll choose to believe that someone on the world wide web will at some point find what I've explained here to be at least mildly useful :).

**Comment by LucyMcGowan** [comment]
Thank you for the detailed response @mkearney! I actually have had the package work quite well in general (I appreciate all the time you've put into it!) I just noticed this and expected a warning, so I thought I'd point it out in case you weren't aware (no rush though). I'm currently in the weeds 🌾 re: authentication/scopes on the google side, so I've been trying out different things & this popped up.

**Comment by mkearney** [comment]
I've included a quick validation check to look for "api.twitter" in an endpoint embedded in the token. I'm going to tentatively close this issue for now, but if you experience any more issues please don't hesitate to mention them!

Thanks again for creating this issue, @LucyMcGowan!
