### ISSUE TITLE
respecting rate-limiting of twitter

### ISSUE THREAD

**Issue by RMHogervorst** [mkearney/rtweet#96]
I'm returning the user friends of my friends. 
This function only returns the 15 or so of my friends' results. This gets confusing:
- I have friends a dataframe of 300 people : 'friends'
- I want their friends as well: 'friends_friends'. 

I apply the function to all of these people
`mutate(friends_friends = map(friends, get_friends))`

However the function get_friends returns only 15 or so people's friends. the rest is 0. 

Could we make the get_friends function respect the rate limiting that twitter imposes? By printing a message to console and implying a timeout?

**Comment by mkearney** [comment]
I don't think I'd want it to be the default, but that seems reasonable. It's certainly annoying to get back 285 blanks like the situation you described above. 

This question has come up regarding `get_followers()` and `search_tweets()` as well so perhaps the answer is to implement a standardized "retryonratelimit" argument that could be set to TRUE in such instances. I'll try to get this added in the next week or so, but while I'll have your attention, I'd like to get your opinion on a related question as well. 

Question: If I'm building in rate limit handlers anyway, do you think I should go ahead and vectorize these functions (`get_friends()`, `get_followers()`, `get_timeline()`, etc.) so they can accept a vector of user names/IDs, too? Previously, my concern with vectorizing was that it'd make it easier for the average user to underestimate or ignore rate limits to their own detriment--e.g., imagine someone doing what you've done above but not figuring out that it only returned 15 due to rate limits. In retrospect, that doesn't seem like such a big deal.

**Comment by RMHogervorst** [comment]
I think you should put the rate limiting in the TWIT.R part, reading the headers on return, but then you have to send the argument along. 
Yes I would love a retryonratelimit argument!

hmm, I would like a vectorized version, but you could make it a separate function if you want to protect the users...
Users will always shoot in their foot I think.  Well you could always warn but not fail (I haven't done any direct request to the twitter API so I don't know what the headers look like, but the [docs](https://dev.twitter.com/rest/public/rate-limiting) are quite clear ). 

I quite like the crul package as a replacement for httr as well, but I'm not sure if that is necessary. You would be rate limited anyways, so multiple requests would likely not work. 

Another thing: Do you set headers in requests? like 
````
ua <- user_agent("http://github.com/mkearney/rtweet")
resp <- GET(url, ua)
```
That might be nice
